const getCoordinates = () => [
  [0, 0],
  [0, 1],
  [0, 2],
  [0, 3],
  [0, 4],
  [0, 5],
  [0, 6],
  [0, 7],
  [0, 8],
  [0, 9],
  [1, 0],
  [1, 1],
  [1, 2],
  [1, 3],
  [1, 4],
  [1, 5],
  [1, 6],
  [1, 7],
  [1, 8],
  [1, 9],
  [2, 0],
  [2, 1],
  [2, 2],
  [2, 3],
  [2, 4],
  [2, 5],
  [2, 6],
  [2, 7],
  [2, 8],
  [2, 9],
  [3, 0],
  [3, 1],
  [3, 2],
  [3, 3],
  [3, 4],
  [3, 5],
  [3, 6],
  [3, 7],
  [3, 8],
  [3, 9],
  [4, 0],
  [4, 1],
  [4, 2],
  [4, 3],
  [4, 4],
  [4, 5],
  [4, 6],
  [4, 7],
  [4, 8],
  [4, 9],
  [5, 0],
  [5, 1],
  [5, 2],
  [5, 3],
  [5, 4],
  [5, 5],
  [5, 6],
  [5, 7],
  [5, 8],
  [5, 9],
  [6, 0],
  [6, 1],
  [6, 2],
  [6, 3],
  [6, 4],
  [6, 5],
  [6, 6],
  [6, 7],
  [6, 8],
  [6, 9],
  [7, 0],
  [7, 1],
  [7, 2],
  [7, 3],
  [7, 4],
  [7, 5],
  [7, 6],
  [7, 7],
  [7, 8],
  [7, 9],
  [8, 0],
  [8, 1],
  [8, 2],
  [8, 3],
  [8, 4],
  [8, 5],
  [8, 6],
  [8, 7],
  [8, 8],
  [8, 9],
  [9, 0],
  [9, 1],
  [9, 2],
  [9, 3],
  [9, 4],
  [9, 5],
  [9, 6],
  [9, 7],
  [9, 8],
  [9, 9],
];

const randomShipPlacements = [
  [
    {
      name: "destroyer",
      coordinates: [
        { y: 7, x: 2 },
        { y: 7, x: 3 },
      ],
    },
    {
      name: "cruiser",
      coordinates: [
        { y: 1, x: 4 },
        { y: 2, x: 4 },
        { y: 3, x: 4 },
      ],
    },
    {
      name: "submarine",
      coordinates: [
        { y: 2, x: 7 },
        { y: 2, x: 8 },
        { y: 2, x: 9 },
      ],
    },
    {
      name: "battleship",
      coordinates: [
        { y: 8, x: 5 },
        { y: 8, x: 6 },
        { y: 8, x: 7 },
        { y: 8, x: 8 },
      ],
    },
    {
      name: "carrier",
      coordinates: [
        { y: 0, x: 0 },
        { y: 1, x: 0 },
        { y: 2, x: 0 },
        { y: 3, x: 0 },
        { y: 4, x: 0 },
      ],
    },
  ],
  [
    {
      name: "destroyer",
      coordinates: [
        { y: 4, x: 5 },
        { y: 5, x: 5 },
      ],
    },
    {
      name: "cruiser",
      coordinates: [
        { y: 9, x: 5 },
        { y: 9, x: 6 },
        { y: 9, x: 7 },
      ],
    },
    {
      name: "submarine",
      coordinates: [
        { y: 0, x: 9 },
        { y: 1, x: 9 },
        { y: 2, x: 9 },
      ],
    },
    {
      name: "battleship",
      coordinates: [
        { y: 2, x: 3 },
        { y: 2, x: 4 },
        { y: 2, x: 5 },
        { y: 2, x: 6 },
      ],
    },
    {
      name: "carrier",
      coordinates: [
        { y: 3, x: 0 },
        { y: 4, x: 0 },
        { y: 5, x: 0 },
        { y: 6, x: 0 },
        { y: 7, x: 0 },
      ],
    },
  ],
  [
    {
      name: "destroyer",
      coordinates: [
        { y: 1, x: 5 },
        { y: 1, x: 6 },
      ],
    },
    {
      name: "cruiser",
      coordinates: [
        { y: 3, x: 9 },
        { y: 4, x: 9 },
        { y: 5, x: 9 },
      ],
    },
    {
      name: "submarine",
      coordinates: [
        { y: 7, x: 4 },
        { y: 7, x: 5 },
        { y: 7, x: 6 },
      ],
    },
    {
      name: "battleship",
      coordinates: [
        { y: 0, x: 0 },
        { y: 0, x: 1 },
        { y: 0, x: 2 },
        { y: 0, x: 3 },
      ],
    },
    {
      name: "carrier",
      coordinates: [
        { y: 9, x: 5 },
        { y: 9, x: 6 },
        { y: 9, x: 7 },
        { y: 9, x: 8 },
        { y: 9, x: 9 },
      ],
    },
  ],
];

export { getCoordinates, randomShipPlacements };
